const MONITORING_USERS_GROUP1_FROM = 1;
const MONITORING_USERS_GROUP1_TO = 63;
const MONITORING_USERS_GROUP2_FROM = 692;
const MONITORING_USERS_GROUP2_TO = 798;

module.exports = {
  MONITORING_USERS_GROUP1_FROM,
  MONITORING_USERS_GROUP1_TO,
  MONITORING_USERS_GROUP2_FROM,
  MONITORING_USERS_GROUP2_TO,
};
